[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
licenser = { id = "org.cadixdev.licenser", version = "0.6.1" }
lombok = { id = "io.freefair.lombok", version = "6.3.0" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version = "1.6.10" }

[versions]
jda = "5.0.0-alpha.5"
chewtils = "2.0-interactions-SNAPSHOT"
guava = "31.0.1-jre"
gson = "2.8.9"
logback = "1.2.10"
nightconfig = "3.6.5"
sqlite = "3.36.0.3"
flyway = "8.4.4"
annotations = "23.0.0"
lombok = "1.18.22"
discord4j = "3.2.1"
graal = "22.0.0"
reflections = "0.10.2"
jdbi = "3.24.1"
junit = "5.8.2"
dotenv = "2.2.3"
netty = "4.1.70.Final"
slf4j = "1.7.32"
fastutil = "8.5.6"

[libraries]
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
chewtils = { module = "pw.chew:jda-chewtils", version.ref = "chewtils" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
nightconfig = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
discord4j = { module = "com.discord4j:discord4j-core", version.ref = "discord4j" }
graal = { module = "org.graalvm.js:js", version.ref = "graal" }
graal-scriptengine = { module = "org.graalvm.js:js-scriptengine", version.ref = "graal" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
jdbi-core = { module = "org.jdbi:jdbi3-core", version.ref = "jdbi" }
jdbi-sqlobject = { module = "org.jdbi:jdbi3-sqlobject", version.ref = "jdbi" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
dotenv = {module = "io.github.cdimascio:dotenv-java", version.ref = "dotenv"}
netty = {module = "io.netty:netty-all", version.ref = "netty"}
slf4japi = {module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
fastutil = {module = "it.unimi.dsi:fastutil", version.ref = "fastutil"}
