name: "Build"

on: [push, pull_request]

jobs:

  validate:
    name: "Validate gradle wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  build:
    name: "Build using Gradle"
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'
          check-latest: true
      - uses: burrunan/gradle-cache-action@v1
        with:
          arguments: clean build
          # Read-only cache if not on repo's default branch: https://stackoverflow.com/a/68414395
          read-only: ${{ format('refs/heads/{0}', github.event.repository.default_branch) != github.ref }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
